site_name: MapMakers Wiki
site_url: https://mapmakersandprogrammers.github.io/Wiki/

theme:
  logo: resources/icon.webp
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  favicon: resources/icon.ico

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Alternativa3D:
      - 'Getting started with Alternativa3D8': pages/Alternativa3D/GettingStartedA3D8/part1.md
      - 'Version history':
          - Alternativa3D5: pages/Alternativa3D/VersionHistory/Alternativa3D5.md
          - Alternativa3D6: pages/Alternativa3D/VersionHistory/Alternativa3D6.md
          - Alternativa3D7: pages/Alternativa3D/VersionHistory/Alternativa3D7.md
          - Alternativa3D8: pages/Alternativa3D/VersionHistory/Alternativa3D8.md
  - About: about.md
